# -*- coding: utf-8 -*-
"""HackatonDuoSamba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjxHrBJhlNO3pEr3JJAy4XbX3zD8E2DT
"""

!pip -q install -U kagglehub

import kagglehub
import pandas as pd


# Download latest version
path = kagglehub.dataset_download("javiersanchezsoriano/roundabout-aerial-images-for-vehicle-detection")

print("Path to dataset files:", path)
df = pd.read_csv(path + "/data.csv")

df.head()

from pathlib import Path

base_path = Path(path)  # lo que devuelve kagglehub
image_rel = df.loc[0, "image_name"]

image_path = base_path / image_rel
print(image_path)

from pathlib import Path
from datetime import datetime
import json, hashlib
import cv2
from collections import Counter

base_path = Path(path)

def resolve_image_path(base_path: Path, image_rel: str) -> Path:
    p = base_path / image_rel
    if p.exists():
        return p
    p2 = base_path / "original" / image_rel  # por si hay doble carpeta
    if p2.exists():
        return p2
    raise FileNotFoundError(f"No se encontró la imagen: {image_rel}")

def metrics_for_image(rows, img_w, img_h):
    counts = Counter(rows["class_name"].tolist())
    total = int(sum(counts.values()))
    area_mpx = (img_w * img_h) / 1e6
    density = total / area_mpx if area_mpx else 0.0

    return {
        "cars": int(counts.get("car", 0)),
        "motorcycles": int(counts.get("motorcycle", 0)),
        "heavy_vehicles": int(counts.get("heavy_vehicle", 0)),
        "total": total,
        "density_v_per_mpx": float(round(density, 4))
    }

def build_report(scene_id, image_name, metrics):
    return {
        "scene_id": scene_id,
        "image_name": image_name,
        "metrics": metrics,
        "timestamp": datetime.utcnow().isoformat() + "Z"
    }

def hash_report(report):
    canonical = json.dumps(report, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode()).hexdigest()

# --- prueba con 1 imagen ---
image_rel = df.loc[0, "image_name"]
rows = df[df["image_name"] == image_rel]

img_path = resolve_image_path(base_path, image_rel)
img = cv2.imread(str(img_path))
h, w = img.shape[:2]

metrics = metrics_for_image(rows, w, h)
report = build_report(scene_id="roundabout_demo", image_name=image_rel, metrics=metrics)
report_hash = hash_report(report)

print("Imagen:", image_rel)
print("Métricas:", metrics)
print("Hash:", report_hash)

!pip -q install ultralytics

print("Filas (vehículos):", len(df))
print("Imágenes únicas:", df["image_name"].nunique())

# Vehículos por imagen (min/medio/max)
vpi = df.groupby("image_name").size()
print("Vehículos por imagen (min, media, max):", int(vpi.min()), float(vpi.mean()), int(vpi.max()))

# Top 5 imágenes con más vehículos
print("\nTop 5 imágenes con más vehículos:")
print(vpi.sort_values(ascending=False).head(5))

# ====== RECREAR image_list y groups (OBLIGATORIO) ======

from pathlib import Path
import random

# Asegúrate de que df ya está cargado
assert "df" in globals(), "df no existe. Vuelve a cargar el CSV primero."

# Agrupar por imagen (1 imagen → N vehículos)
groups = df.groupby("image_name", sort=False)

# Lista de imágenes únicas
image_list = list(groups.groups.keys())

print("Imágenes únicas:", len(image_list))

# Mezclar para no sesgar
random.seed(42)
random.shuffle(image_list)

# ====== CELDA BASE (OBLIGATORIA - CORREGIDA) ======

import pandas as pd
import kagglehub
from pathlib import Path
import random

# 1) Descargar dataset (cache, sin auth)
path = kagglehub.dataset_download(
    "javiersanchezsoriano/roundabout-aerial-images-for-vehicle-detection"
)
base_path = Path(path)

# 2) Cargar CSV
df = pd.read_csv(base_path / "data.csv")

# 3) Limpieza mínima
df = df.dropna(subset=["class_name", "image_name", "x_min", "y_min", "x_max", "y_max"])
df["class_name"] = df["class_name"].astype(str).str.lower()

# 4) MAPEO SEMÁNTICO DE CLASES (CRUCIAL)
mapa_clases = {
    "car": "car",
    "cycle": "motorcycle",
    "truck": "heavy_vehicle",
    "bus": "heavy_vehicle"
}

df["class_name"] = df["class_name"].map(mapa_clases)
df = df.dropna(subset=["class_name"])  # elimina clases no usadas

# 5) Clases finales (ORDEN FIJO)
classes = ["car", "motorcycle", "heavy_vehicle"]
class_to_id = {c: i for i, c in enumerate(classes)}

print("Clases finales:", class_to_id)

# 6) Agrupar por imagen
groups = df.groupby("image_name", sort=False)
image_list = list(groups.groups.keys())

random.seed(42)
random.shuffle(image_list)

print("Imágenes únicas:", len(image_list))

!pip -q install pandas opencv-python ultralytics kagglehub pyyaml

!rm -rf /content/yolo_roundabout

import shutil
from pathlib import Path
import random
import cv2
from shutil import copy2

# --- Rehacer estructura desde cero ---
yolo_root = Path("/content/yolo_roundabout")
if yolo_root.exists():
    shutil.rmtree(yolo_root)

images_dir = yolo_root / "images"
labels_dir = yolo_root / "labels"
for split in ["train", "val"]:
    (images_dir / split).mkdir(parents=True, exist_ok=True)
    (labels_dir / split).mkdir(parents=True, exist_ok=True)

# Usar subset
LIMIT = 2500
subset = image_list[:LIMIT]
random.seed(42)
random.shuffle(subset)

val_ratio = 0.1
val_n = max(1, int(val_ratio * len(subset)))
val_set = set(subset[:val_n])
train_set = set(subset[val_n:])

print("Train images:", len(train_set), "Val images:", len(val_set))

def bbox_to_yolo(xmin, ymin, xmax, ymax, w, h):
    xmin = max(0.0, min(float(xmin), w - 1))
    xmax = max(0.0, min(float(xmax), w - 1))
    ymin = max(0.0, min(float(ymin), h - 1))
    ymax = max(0.0, min(float(ymax), h - 1))
    bw = max(1.0, xmax - xmin)
    bh = max(1.0, ymax - ymin)
    cx = xmin + bw / 2.0
    cy = ymin + bh / 2.0
    return cx / w, cy / h, bw / w, bh / h

# Reprocesar subset
for i, image_rel in enumerate(subset, 1):
    split = "val" if image_rel in val_set else "train"

    img_path = resolve_image_path(base_path, image_rel)
    img = cv2.imread(str(img_path))
    if img is None:
        continue
    h, w = img.shape[:2]

    stem = Path(image_rel).name
    out_img = images_dir / split / stem
    copy2(img_path, out_img)

    rows = groups.get_group(image_rel)
    lines = []
    for _, r in rows.iterrows():
        cls_id = class_to_id[r["class_name"]]  # YA MAPEADA
        cx, cy, bw, bh = bbox_to_yolo(
            r["x_min"], r["y_min"], r["x_max"], r["y_max"], w, h
        )
        lines.append(f"{cls_id} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}")

    out_lbl = labels_dir / split / (Path(stem).stem + ".txt")
    out_lbl.write_text("\n".join(lines) + "\n")

    if i % 500 == 0:
        print("Procesadas:", i)

print("✅ Train imgs:", len(list((images_dir/'train').glob('*'))))
print("✅ Val imgs:",   len(list((images_dir/'val').glob('*'))))

import yaml
data_yaml = {"path": str(yolo_root), "train": "images/train", "val": "images/val", "nc": len(classes), "names": classes}
yaml_path = yolo_root / "data.yaml"
yaml_path.write_text(yaml.safe_dump(data_yaml, sort_keys=False))
print("✅ data.yaml:", yaml_path, "exists:", yaml_path.exists())

from ultralytics import YOLO
model = YOLO("yolov8m.pt")
model.train(data=str(yaml_path), epochs=40, imgsz=1024, cache=True, batch=8, workers=8, device=0, save_period=10, val=False, amp=True, name="yolov8m_roundabout_fast")

!nvidia-smi

!ls -lah /content/runs/detect

!ls -lah /content/runs/detect/train/weights

from google.colab import drive
drive.mount('/content/drive')

!cp /content/runs/detect/train/weights/best.pt /content/drive/MyDrive/best_roundabout.pt
!cp /content/yolo_roundabout/data.yaml /content/drive/MyDrive/data_roundabout.yaml

from google.colab import drive
drive.mount("/content/drive")

import shutil
from pathlib import Path

# ⚠️ UPDATE THIS RUN NAME if needed
src = Path("/content/runs/detect/yolov8m_roundabout_fast5/weights/best.pt")
dst = Path("/content/drive/MyDrive/yolo_models/best_roundabout.pt")

dst.parent.mkdir(parents=True, exist_ok=True)
shutil.copy(src, dst)

print("✅ Modelo guardado en Drive:", dst)

from google.colab import files
files.download("/content/drive/MyDrive/yolo_models/best_roundabout.pt")

!ls /content/drive/MyDrive/yolo_models

!ls /content/runs/detect/yolov8m_roundabout_fast5/weights

from google.colab import files
files.download("/content/runs/detect/train/weights/best.pt")

from ultralytics import YOLO

model = YOLO("/content/runs/detect/train/weights/best.pt")

image_path = "/content/sec4_frame_000002.png"  # cambia el nombre si es otro

results = model(image_path)[0]
print("Vehículos detectados:", len(results.boxes))

import matplotlib.pyplot as plt

img_with_boxes = results.plot()  # dibuja las cajas
plt.figure(figsize=(10,6))
plt.imshow(img_with_boxes)
plt.axis("off")
plt.show()